[servers.oj]
proxy = "socks5://easyconn:1080"
listen_host = "0.0.0.0"
listen_port = 10001
upstream_host = "10.1.1.1"
upstream_port = 9000
upstream_ssl = false

[servers.oj_backend]
proxy = "socks5://easyconn:1080"
listen_host = "0.0.0.0"
listen_port = 10002
upstream_host = "10.1.1.1"
upstream_port = 9001
upstream_ssl = false